"""All tables from SPEC section 3.1. Importing this package registers them on Base.metadata."""

from app.db.models.audit import (
    PARTITIONED_TABLES,
    AccessEvent,
    AccessExplanation,
    Alert,
    AlertReview,
    AnchorReceipt,
    AuditEvent,
    BreakGlassEvent,
    MerkleCheckpoint,
    PatientAccessQuery,
    PolicyVersion,
)
from app.db.models.billing import Invoice, InvoiceItem, Payment, Service
from app.db.models.clinical import (
    Allergy,
    ClinicalNote,
    Condition,
    Document,
    LabOrder,
    LabResult,
    Prescription,
    Vital,
)
from app.db.models.consent import Consent, ConsentEvent, ConsentNotice
from app.db.models.system import Job, PushSubscription
from app.db.models.tenancy import (
    Clinic,
    Device,
    EmailOtp,
    Membership,
    MfaSecret,
    Patient,
    StaffProfile,
    User,
    UserSession,
)
from app.db.models.workflow import (
    Appointment,
    CareTeamAssignment,
    Encounter,
    QueueToken,
    Referral,
    Schedule,
    Shift,
)

__all__ = [
    "PARTITIONED_TABLES",
    "AccessEvent",
    "AccessExplanation",
    "Alert",
    "AlertReview",
    "Allergy",
    "AnchorReceipt",
    "Appointment",
    "AuditEvent",
    "BreakGlassEvent",
    "CareTeamAssignment",
    "Clinic",
    "ClinicalNote",
    "Condition",
    "Consent",
    "ConsentEvent",
    "ConsentNotice",
    "Device",
    "Document",
    "EmailOtp",
    "Encounter",
    "Invoice",
    "InvoiceItem",
    "Job",
    "LabOrder",
    "LabResult",
    "Membership",
    "MerkleCheckpoint",
    "MfaSecret",
    "Patient",
    "PatientAccessQuery",
    "Payment",
    "PolicyVersion",
    "Prescription",
    "PushSubscription",
    "QueueToken",
    "Referral",
    "Schedule",
    "Service",
    "Shift",
    "StaffProfile",
    "User",
    "UserSession",
    "Vital",
]
